from pathlib import Path
from typing import Dict, List

import numpy as np


def read_ply_xyz(path: str) -> Dict[str, np.ndarray]:
    path = str(path)
    try:
        from plyfile import PlyData
        ply = PlyData.read(path)
        v = ply['vertex']
        out = {
            'x': np.asarray(v['x'], dtype=np.float64),
            'y': np.asarray(v['y'], dtype=np.float64),
            'z': np.asarray(v['z'], dtype=np.float64),
        }
        for key in ['red', 'green', 'blue', 'nx', 'ny', 'nz']:
            if key in v.data.dtype.names:
                out[key] = np.asarray(v[key])
        return out
    except Exception:
        pass
    try:
        import open3d as o3d
        pcd = o3d.io.read_point_cloud(path)
        pts = np.asarray(pcd.points, dtype=np.float64)
        out = {'x': pts[:, 0], 'y': pts[:, 1], 'z': pts[:, 2]}
        if len(pcd.normals) > 0:
            n = np.asarray(pcd.normals, dtype=np.float64)
            out['nx'], out['ny'], out['nz'] = n[:, 0], n[:, 1], n[:, 2]
        if len(pcd.colors) > 0:
            c = (np.asarray(pcd.colors, dtype=np.float64) * 255.0).clip(0, 255).astype(np.uint8)
            out['red'], out['green'], out['blue'] = c[:, 0], c[:, 1], c[:, 2]
        return out
    except Exception as e:
        raise RuntimeError('读取 PLY 失败。请安装 plyfile 或 open3d。') from e


def _ply_type_from_numpy_dtype(dt: np.dtype) -> str:
    dt = np.dtype(dt)
    kind = dt.kind
    size = dt.itemsize
    if kind == 'i':
        return {1: 'char', 2: 'short', 4: 'int', 8: 'int'}[size]
    if kind == 'u':
        return {1: 'uchar', 2: 'ushort', 4: 'uint', 8: 'uint'}[size]
    if kind == 'f':
        return {4: 'float', 8: 'double'}[size]
    raise TypeError(f'不支持的 PLY 字段类型: {dt}')


def _make_le_dtype(dtype_in: np.dtype) -> np.dtype:
    descr = []
    for name in dtype_in.names:
        dt = dtype_in.fields[name][0]
        if dt.subdtype is not None:
            raise TypeError(f'暂不支持子数组字段: {name} -> {dt}')
        descr.append((name, dt.newbyteorder('<')))
    return np.dtype(descr)


def _build_ply_header(
    dtype_out: np.dtype,
    n_points: int,
    comment: str = 'Generated by hyperspectral_pointcloud_fusion',
) -> bytes:
    lines = ['ply', 'format binary_little_endian 1.0', f'comment {comment}', f'element vertex {n_points}']
    for name in dtype_out.names:
        dt = dtype_out.fields[name][0]
        lines.append(f'property {_ply_type_from_numpy_dtype(dt)} {name}')
    lines.append('end_header')
    return ('\n'.join(lines) + '\n').encode('ascii')


def write_binary_vertex_ply(path: str, field_arrays: Dict[str, np.ndarray], chunk_size: int = 500000) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    if not field_arrays:
        raise ValueError('field_arrays 不能为空')
    names = list(field_arrays.keys())
    lengths = {len(np.asarray(field_arrays[name])) for name in names}
    if len(lengths) != 1:
        raise ValueError('所有字段长度必须一致')
    n = lengths.pop()
    descr = []
    arrays: Dict[str, np.ndarray] = {}
    for name in names:
        arr = np.asarray(field_arrays[name])
        if arr.ndim != 1:
            raise ValueError(f'字段必须是一维数组: {name}')
        arrays[name] = arr
        descr.append((name, arr.dtype))
    dtype_out = _make_le_dtype(np.dtype(descr))
    header = _build_ply_header(dtype_out, n)
    with open(path, 'wb') as f:
        f.write(header)
        for i0 in range(0, n, max(1, int(chunk_size))):
            i1 = min(n, i0 + max(1, int(chunk_size)))
            out_arr = np.empty(i1 - i0, dtype=dtype_out)
            for name in names:
                out_arr[name] = np.asarray(arrays[name][i0:i1], dtype=dtype_out.fields[name][0])
            np.ascontiguousarray(out_arr).tofile(f)


def write_binary_rgb_ply(path: str, xyz: np.ndarray, rgb: np.ndarray, extra: Dict[str, np.ndarray] | None = None) -> None:
    extra = extra or {}
    field_arrays: Dict[str, np.ndarray] = {
        'x': np.asarray(xyz[:, 0], dtype=np.float64),
        'y': np.asarray(xyz[:, 1], dtype=np.float64),
        'z': np.asarray(xyz[:, 2], dtype=np.float64),
        'red': np.asarray(rgb[:, 0], dtype=np.uint8),
        'green': np.asarray(rgb[:, 1], dtype=np.uint8),
        'blue': np.asarray(rgb[:, 2], dtype=np.uint8),
    }
    for key, arr in extra.items():
        field_arrays[key] = np.asarray(arr)
    write_binary_vertex_ply(path, field_arrays)


def write_binary_spectra_ply(path: str, xyz: np.ndarray, spectra: np.ndarray, band_names: List[str], rgb: np.ndarray | None = None, extra: Dict[str, np.ndarray] | None = None) -> None:
    if spectra.ndim != 2:
        raise ValueError('spectra 必须为二维数组')
    n, b = spectra.shape
    if xyz.shape[0] != n:
        raise ValueError('xyz 与 spectra 的点数不一致')
    if len(band_names) != b:
        raise ValueError('band_names 数量与 spectra 列数不一致')
    field_arrays: Dict[str, np.ndarray] = {
        'x': np.asarray(xyz[:, 0], dtype=np.float64),
        'y': np.asarray(xyz[:, 1], dtype=np.float64),
        'z': np.asarray(xyz[:, 2], dtype=np.float64),
    }
    for i, name in enumerate(band_names):
        field_arrays[name] = np.asarray(spectra[:, i], dtype=np.float32)
    if rgb is not None:
        field_arrays['red'] = np.asarray(rgb[:, 0], dtype=np.uint8)
        field_arrays['green'] = np.asarray(rgb[:, 1], dtype=np.uint8)
        field_arrays['blue'] = np.asarray(rgb[:, 2], dtype=np.uint8)
    extra = extra or {}
    for key, arr in extra.items():
        field_arrays[key] = np.asarray(arr)
    write_binary_vertex_ply(path, field_arrays)
